library(shiny)
library(dplyr)
library(DT)
library(stringr)
library(rmarkdown)
library(ppcor)
library(shinyjs)
library(shinyalert)
################W
library(plotly)
library(Hmisc)
library(kableExtra)

source("data_collection1.R")
source("data_collection2.R")
source("report_ui.R")
ui = (htmlOutput("page"))